version: '3.8'

services:
  android:
    # Use pre-built image from GitHub Container Registry
    # To build locally instead, comment out 'image:' and uncomment 'build:' section below
    image: ghcr.io/richardpowellus/android-docker-arm:latest
    
    # Uncomment to build locally:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    
    container_name: waydroid-android
    privileged: true
    # Waydroid requires privileged mode for LXC containers
    ports:
      - "5900:5900"  # VNC port
      - "6080:6080"  # noVNC web interface
    environment:
      - DISPLAY=:99
      - VNC_PASSWORD=${VNC_PASSWORD:-android}
    volumes:
      - waydroid-data:/var/lib/waydroid
      - waydroid-home:/root/.local/share/waydroid
      - avd-data:/root/.android/avd
    restart: unless-stopped
    stdin_open: true
    tty: true
    shm_size: '2gb'
    command: /start.sh

volumes:
  waydroid-data:
    driver: local
  waydroid-home:
    driver: local
