version: '3.8'

services:
  android:
    # Use pre-built image from GitHub Container Registry
    # To build locally instead, comment out 'image:' and uncomment 'build:' section below
    image: ghcr.io/richardpowellus/android-docker-arm:latest
    
    # Uncomment to build locally:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    
    container_name: android-emulator
    privileged: true
    # Remove 'privileged: true' and uncomment devices below if KVM is available for better security
    # devices:
    #   - /dev/kvm:/dev/kvm
    ports:
      - "5900:5900"  # VNC port
      - "6080:6080"  # noVNC web interface
      - "5555:5555"  # ADB port (optional, for debugging)
    environment:
      - DISPLAY=:99
      - VNC_PASSWORD=${VNC_PASSWORD:-android}
      - EMULATOR_NAME=android_emulator
      - EMULATOR_MEMORY=${EMULATOR_MEMORY:-4096}
      - EMULATOR_CORES=${EMULATOR_CORES:-4}
    volumes:
      - android-data:/root/.android
      - avd-data:/root/.android/avd
    restart: unless-stopped
    stdin_open: true
    tty: true
    shm_size: '2gb'

volumes:
  android-data:
    driver: local
  avd-data:
    driver: local
