version: '3.8'

services:
  android:
    # Use redroid official image directly
    image: redroid/redroid:16.0.0_64only-latest
    
    container_name: redroid-android
    privileged: true
    # redroid requires privileged mode for binder devices
    ports:
      - "5555:5555"  # ADB port
    environment:
      - androidboot.redroid_width=1920
      - androidboot.redroid_height=1080
      - androidboot.redroid_dpi=320
      - androidboot.redroid_gpu_mode=guest
    volumes:
      - redroid-data:/data
    restart: unless-stopped
    stdin_open: true
    tty: true
    shm_size: '2gb'

volumes:
  redroid-data:
    driver: local
