# Docker Compose file optimized for Portainer
# This version uses the pre-built image from GitHub Container Registry

version: '3.8'

services:
  android-whatsapp:
    image: ghcr.io/richardpowellus/android-docker-arm:latest
    container_name: android-whatsapp-arm64
    privileged: true
    ports:
      - "5900:5900"  # VNC port
      - "6080:6080"  # noVNC web interface
      - "5555:5555"  # ADB port (optional, for debugging)
    environment:
      - DISPLAY=:99
      - VNC_PASSWORD=${VNC_PASSWORD:-android}
      - EMULATOR_NAME=android_arm64
      - EMULATOR_MEMORY=${EMULATOR_MEMORY:-4096}
      - EMULATOR_CORES=${EMULATOR_CORES:-4}
    volumes:
      - android-data:/root/.android
      - avd-data:/root/.android/avd
    restart: unless-stopped
    stdin_open: true
    tty: true
    # Comment out the devices section if KVM is not available
    # devices:
    #   - /dev/kvm:/dev/kvm
    shm_size: '2gb'

volumes:
  android-data:
    driver: local
  avd-data:
    driver: local
